/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignUpSuccessRouteImport } from './routes/auth/sign-up-success'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as ProtectedFlightHistoryRouteImport } from './routes/_protected/flight/history'
import { Route as ProtectedFlightMapRouteImport } from './routes/_protected/flight/map'
import { Route as ProtectedFundDashboardRouteImport } from './routes/_protected/fund/dashboard'
import { Route as ProtectedFundEventsIndexRouteImport } from './routes/_protected/fund/events/index'
import { Route as ProtectedFundEventsEventRouteImport } from './routes/_protected/fund/events/$event'
import { Route as ProtectedFundPerformanceYearRouteImport } from './routes/_protected/fund/performance/$year'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpSuccessRoute = AuthSignUpSuccessRouteImport.update({
  id: '/auth/sign-up-success',
  path: '/auth/sign-up-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedFlightHistoryRoute = ProtectedFlightHistoryRouteImport.update({
  id: '/flight/history',
  path: '/flight/history',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFlightMapRoute = ProtectedFlightMapRouteImport.update({
  id: '/flight/map',
  path: '/flight/map',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFundDashboardRoute = ProtectedFundDashboardRouteImport.update({
  id: '/fund/dashboard',
  path: '/fund/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFundEventsIndexRoute =
  ProtectedFundEventsIndexRouteImport.update({
    id: '/fund/events/',
    path: '/fund/events/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedFundEventsEventRoute =
  ProtectedFundEventsEventRouteImport.update({
    id: '/fund/events/$event',
    path: '/fund/events/$event',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedFundPerformanceYearRoute =
  ProtectedFundPerformanceYearRouteImport.update({
    id: '/fund/performance/$year',
    path: '/fund/performance/$year',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedRouteRouteWithChildren
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sign-up-success': typeof AuthSignUpSuccessRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/flight/history': typeof ProtectedFlightHistoryRoute
  '/flight/map': typeof ProtectedFlightMapRoute
  '/fund/dashboard': typeof ProtectedFundDashboardRoute
  '/fund/events/$event': typeof ProtectedFundEventsEventRoute
  '/fund/performance/$year': typeof ProtectedFundPerformanceYearRoute
  '/fund/events/': typeof ProtectedFundEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedRouteRouteWithChildren
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sign-up-success': typeof AuthSignUpSuccessRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/flight/history': typeof ProtectedFlightHistoryRoute
  '/flight/map': typeof ProtectedFlightMapRoute
  '/fund/dashboard': typeof ProtectedFundDashboardRoute
  '/fund/events/$event': typeof ProtectedFundEventsEventRoute
  '/fund/performance/$year': typeof ProtectedFundPerformanceYearRoute
  '/fund/events': typeof ProtectedFundEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sign-up-success': typeof AuthSignUpSuccessRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/_protected/flight/history': typeof ProtectedFlightHistoryRoute
  '/_protected/flight/map': typeof ProtectedFlightMapRoute
  '/_protected/fund/dashboard': typeof ProtectedFundDashboardRoute
  '/_protected/fund/events/$event': typeof ProtectedFundEventsEventRoute
  '/_protected/fund/performance/$year': typeof ProtectedFundPerformanceYearRoute
  '/_protected/fund/events/': typeof ProtectedFundEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth/sign-up-success'
    | '/auth/update-password'
    | '/flight/history'
    | '/flight/map'
    | '/fund/dashboard'
    | '/fund/events/$event'
    | '/fund/performance/$year'
    | '/fund/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth/sign-up-success'
    | '/auth/update-password'
    | '/flight/history'
    | '/flight/map'
    | '/fund/dashboard'
    | '/fund/events/$event'
    | '/fund/performance/$year'
    | '/fund/events'
  id:
    | '__root__'
    | '/_protected'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth/sign-up-success'
    | '/auth/update-password'
    | '/_protected/flight/history'
    | '/_protected/flight/map'
    | '/_protected/fund/dashboard'
    | '/_protected/fund/events/$event'
    | '/_protected/fund/performance/$year'
    | '/_protected/fund/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthSignUpSuccessRoute: typeof AuthSignUpSuccessRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up-success': {
      id: '/auth/sign-up-success'
      path: '/auth/sign-up-success'
      fullPath: '/auth/sign-up-success'
      preLoaderRoute: typeof AuthSignUpSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/flight/history': {
      id: '/_protected/flight/history'
      path: '/flight/history'
      fullPath: '/flight/history'
      preLoaderRoute: typeof ProtectedFlightHistoryRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/flight/map': {
      id: '/_protected/flight/map'
      path: '/flight/map'
      fullPath: '/flight/map'
      preLoaderRoute: typeof ProtectedFlightMapRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/fund/dashboard': {
      id: '/_protected/fund/dashboard'
      path: '/fund/dashboard'
      fullPath: '/fund/dashboard'
      preLoaderRoute: typeof ProtectedFundDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/fund/events/': {
      id: '/_protected/fund/events/'
      path: '/fund/events'
      fullPath: '/fund/events/'
      preLoaderRoute: typeof ProtectedFundEventsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/fund/events/$event': {
      id: '/_protected/fund/events/$event'
      path: '/fund/events/$event'
      fullPath: '/fund/events/$event'
      preLoaderRoute: typeof ProtectedFundEventsEventRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/fund/performance/$year': {
      id: '/_protected/fund/performance/$year'
      path: '/fund/performance/$year'
      fullPath: '/fund/performance/$year'
      preLoaderRoute: typeof ProtectedFundPerformanceYearRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedFlightHistoryRoute: typeof ProtectedFlightHistoryRoute
  ProtectedFlightMapRoute: typeof ProtectedFlightMapRoute
  ProtectedFundDashboardRoute: typeof ProtectedFundDashboardRoute
  ProtectedFundEventsEventRoute: typeof ProtectedFundEventsEventRoute
  ProtectedFundPerformanceYearRoute: typeof ProtectedFundPerformanceYearRoute
  ProtectedFundEventsIndexRoute: typeof ProtectedFundEventsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedFlightHistoryRoute: ProtectedFlightHistoryRoute,
  ProtectedFlightMapRoute: ProtectedFlightMapRoute,
  ProtectedFundDashboardRoute: ProtectedFundDashboardRoute,
  ProtectedFundEventsEventRoute: ProtectedFundEventsEventRoute,
  ProtectedFundPerformanceYearRoute: ProtectedFundPerformanceYearRoute,
  ProtectedFundEventsIndexRoute: ProtectedFundEventsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthSignUpSuccessRoute: AuthSignUpSuccessRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
