-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

CREATE TABLE dim.asset (
  id          smallint        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  asset_class dim.asset_class NOT NULL,
  ticker      text            NOT NULL,
  name        text            NOT NULL,
  currency_id smallint        NOT NULL,
  logo_url    text
);

ALTER TABLE dim.asset
  ADD CONSTRAINT assets_pkey PRIMARY KEY (id);

ALTER TABLE dim.asset
  ADD CONSTRAINT assets_ticker_key UNIQUE (ticker);

CREATE TABLE dim.currency (
  id       smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  iso_code text     NOT NULL
);

ALTER TABLE dim.currency
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE dim.currency
  ADD CONSTRAINT currency_iso_code_key UNIQUE (iso_code);

ALTER TABLE dim.currency
  ADD CONSTRAINT currency_pkey PRIMARY KEY (id);

ALTER TABLE dim.asset
  ADD CONSTRAINT assets_currency_fkey FOREIGN KEY (currency_id) REFERENCES dim.currency(id) ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE TABLE dim.user_settings (
  user_id         uuid NOT NULL,
  dnse_account_id text,
  inception_date  date DEFAULT '2020-01-01'::date NOT NULL,
  display_name    text,
  avatar          text
);

ALTER TABLE dim.user_settings
  ADD CONSTRAINT user_settings_dnse_account_id_key UNIQUE (dnse_account_id);

ALTER TABLE dim.user_settings
  ADD CONSTRAINT user_settings_pkey PRIMARY KEY (user_id);

ALTER TABLE dim.user_settings
  ADD CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE dwd.daily_asset_close (
  asset_id smallint      NOT NULL,
  date     date          NOT NULL,
  close    numeric(14,2) NOT NULL
);

ALTER TABLE dwd.daily_asset_close
  ADD CONSTRAINT asset_close_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES dim.asset(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE dwd.daily_asset_close
  ADD CONSTRAINT asset_close_pkey PRIMARY KEY (asset_id, date) INCLUDE (close);

CREATE TRIGGER after_new_prices_ins
  AFTER INSERT ON dwd.daily_asset_close REFERENCING NEW TABLE AS new_rows
  FOR EACH STATEMENT
  EXECUTE FUNCTION public.trg_snapshots_prices();

CREATE TRIGGER after_new_prices_upd
  AFTER UPDATE ON dwd.daily_asset_close REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows
  FOR EACH STATEMENT
  EXECUTE FUNCTION public.trg_snapshots_prices();

CREATE TABLE dwd.daily_fxrate_close (
  currency_id smallint      NOT NULL,
  date        date          NOT NULL,
  close       numeric(14,2) NOT NULL
);

ALTER TABLE dwd.daily_fxrate_close
  ADD CONSTRAINT exchange_rates_currency_code_fkey FOREIGN KEY (currency_id) REFERENCES dim.currency(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE dwd.daily_fxrate_close
  ADD CONSTRAINT exchange_rates_pkey PRIMARY KEY (currency_id, date) INCLUDE (close);

CREATE TRIGGER after_new_fxrate_ins
  AFTER INSERT ON dwd.daily_fxrate_close REFERENCING NEW TABLE AS new_rows
  FOR EACH STATEMENT
  EXECUTE FUNCTION public.trg_snapshots_fxrate();

CREATE TRIGGER after_new_fxrate_upd
  AFTER UPDATE ON dwd.daily_fxrate_close REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows
  FOR EACH STATEMENT
  EXECUTE FUNCTION public.trg_snapshots_fxrate();

CREATE TABLE dwd.tx_borrow (
  tx_id     integer       NOT NULL,
  lender    text          NOT NULL,
  principal numeric(16,0) NOT NULL,
  rate      numeric(6,2)  NOT NULL
);

ALTER TABLE dwd.tx_borrow
  ADD CONSTRAINT tx_borrow_pkey PRIMARY KEY (tx_id);

CREATE TRIGGER after_new_tx_borrow
  AFTER INSERT ON dwd.tx_borrow
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_process_tx_borrow();

CREATE TABLE dwd.tx_cashflow (
  tx_id       integer          NOT NULL,
  asset_id    smallint         NOT NULL,
  operation   dim.cashflow_ops NOT NULL,
  quantity    numeric(18,2)    NOT NULL,
  fx_rate     numeric(10,2)    DEFAULT 1 NOT NULL,
  net_proceed numeric          GENERATED ALWAYS AS ((quantity * fx_rate)) STORED NOT NULL
);

ALTER TABLE dwd.tx_cashflow
  ADD CONSTRAINT tx_cashflow_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES dim.asset(id) ON UPDATE CASCADE;

ALTER TABLE dwd.tx_cashflow
  ADD CONSTRAINT tx_cashflow_pkey PRIMARY KEY (tx_id, asset_id);

CREATE TRIGGER after_new_tx_cashflow
  AFTER INSERT ON dwd.tx_cashflow
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_process_tx_cashflow();

CREATE TABLE dwd.tx_entries (
  id         integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id    uuid                     NOT NULL,
  category   dim.tx_category          NOT NULL,
  memo       text                     NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE dwd.tx_entries
  ADD CONSTRAINT tx_entries_pkey PRIMARY KEY (id);

ALTER TABLE dwd.tx_borrow
  ADD CONSTRAINT tx_borrow_tx_id_fkey FOREIGN KEY (tx_id) REFERENCES dwd.tx_entries(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE dwd.tx_cashflow
  ADD CONSTRAINT tx_cashflow_tx_id_fkey FOREIGN KEY (tx_id) REFERENCES dwd.tx_entries(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE dwd.tx_entries
  ADD CONSTRAINT tx_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE dwd.tx_legs (
  tx_id    integer       NOT NULL,
  asset_id smallint      NOT NULL,
  quantity numeric(18,2) NOT NULL,
  debit    numeric(16,0) NOT NULL,
  credit   numeric(16,0) NOT NULL
);

ALTER TABLE dwd.tx_legs
  ADD CONSTRAINT tx_legs_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES dim.asset(id) ON UPDATE CASCADE;

ALTER TABLE dwd.tx_legs
  ADD CONSTRAINT tx_legs_pkey PRIMARY KEY (tx_id, asset_id);

ALTER TABLE dwd.tx_legs
  ADD CONSTRAINT tx_legs_tx_id_fkey FOREIGN KEY (tx_id) REFERENCES dwd.tx_entries(id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TRIGGER after_new_tx_legs
  AFTER INSERT ON dwd.tx_legs REFERENCING NEW TABLE AS new_rows
  FOR EACH STATEMENT
  EXECUTE FUNCTION public.trg_snapshots_tx_legs();

CREATE TABLE dwd.tx_repay (
  tx_id       integer       NOT NULL,
  borrow_tx   integer       NOT NULL,
  principal   numeric(16,0) NOT NULL,
  interest    numeric(16,0) NOT NULL,
  net_proceed numeric(16,0) GENERATED ALWAYS AS ((principal + interest)) STORED NOT NULL
);

ALTER TABLE dwd.tx_repay
  ADD CONSTRAINT tx_repay_borrow_tx_fkey FOREIGN KEY (borrow_tx) REFERENCES dwd.tx_borrow(tx_id) ON UPDATE CASCADE;

ALTER TABLE dwd.tx_repay
  ADD CONSTRAINT tx_repay_pkey PRIMARY KEY (tx_id);

ALTER TABLE dwd.tx_repay
  ADD CONSTRAINT tx_repay_tx_id_fkey FOREIGN KEY (tx_id) REFERENCES dwd.tx_entries(id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TRIGGER after_new_tx_repay
  AFTER INSERT ON dwd.tx_repay
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_process_tx_repay();

CREATE TABLE dwd.tx_stock (
  tx_id       integer       NOT NULL,
  stock_id    smallint      NOT NULL,
  price       numeric(9,0)  DEFAULT 0 NOT NULL,
  quantity    numeric(9,0)  NOT NULL,
  fee         numeric(16,0) NOT NULL,
  tax         numeric(16,0) DEFAULT 0 NOT NULL,
  operation   dim.stock_ops NOT NULL,
  net_proceed numeric(16,0) GENERATED ALWAYS AS (
CASE
    WHEN (operation = 'buy'::dim.stock_ops) THEN (((price * quantity) + fee) + tax)
    WHEN (operation = 'sell'::dim.stock_ops) THEN (((price * quantity) - fee) - tax)
    ELSE (0)::numeric
END) STORED NOT NULL
);

ALTER TABLE dwd.tx_stock
  ADD CONSTRAINT tx_stock_pkey PRIMARY KEY (tx_id);

ALTER TABLE dwd.tx_stock
  ADD CONSTRAINT tx_stock_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES dim.asset(id) ON UPDATE CASCADE;

ALTER TABLE dwd.tx_stock
  ADD CONSTRAINT tx_stock_tx_id_fkey FOREIGN KEY (tx_id) REFERENCES dwd.tx_entries(id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TRIGGER after_new_tx_stock
  AFTER INSERT ON dwd.tx_stock
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_process_tx_stock();

CREATE TABLE dws.daily_snapshots (
  snapshot_date     date    NOT NULL,
  user_id           uuid    NOT NULL,
  total_equity      numeric,
  intraday_cashflow numeric,
  intraday_fee      numeric,
  intraday_tax      numeric,
  intraday_interest numeric,
  total_cashflow    numeric,
  intraday_pnl      numeric,
  intraday_return   numeric
);

ALTER TABLE dws.daily_snapshots
  ADD CONSTRAINT daily_snapshots_pkey PRIMARY KEY (user_id, snapshot_date);

ALTER TABLE dws.daily_snapshots
  ADD CONSTRAINT daily_snapshots_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE SCHEMA ods AUTHORIZATION postgres;

CREATE TABLE ods.dnse_m1_close (
  symbol       text                     NOT NULL,
  close        numeric                  NOT NULL,
  volume       bigint                   NOT NULL,
  last_updated timestamp with time zone NOT NULL,
  received_at  timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ods.dnse_m1_close
  ADD CONSTRAINT dnse_m1_close_pkey PRIMARY KEY (symbol, last_updated);

CREATE TRIGGER after_new_m1_close
  AFTER INSERT ON ods.dnse_m1_close
  FOR EACH ROW
  EXECUTE FUNCTION public.upsert_historical_prices();

CREATE TABLE ods.dnse_order_events (
  id                integer                  NOT NULL,
  side              text                     NOT NULL,
  account_no        text                     NOT NULL,
  symbol            text                     NOT NULL,
  order_type        text                     NOT NULL,
  price             numeric                  NOT NULL,
  quantity          integer                  NOT NULL,
  fill_quantity     integer                  DEFAULT 0 NOT NULL,
  canceled_quantity integer                  DEFAULT 0 NOT NULL,
  leave_quantity    integer                  DEFAULT 0 NOT NULL,
  order_status      text                     NOT NULL,
  loan_package_id   integer,
  modified_date     timestamp with time zone NOT NULL,
  received_at       timestamp with time zone DEFAULT now() NOT NULL,
  avg_price         numeric,
  tax               numeric,
  fee               numeric
);

ALTER TABLE ods.dnse_order_events
  ADD CONSTRAINT dnse_order_events_pkey PRIMARY KEY (received_at);

CREATE TRIGGER after_filled_dnse_orders
  AFTER INSERT ON ods.dnse_order_events
  FOR EACH ROW
  EXECUTE FUNCTION public.process_dnse_order();

CREATE TABLE ods.news_articles (
  id             integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title          text                     NOT NULL,
  url            text                     NOT NULL,
  source         text                     NOT NULL,
  published_at   timestamp with time zone,
  excerpt        text,
  related_stocks text[]                   DEFAULT '{}'::text[]
);

ALTER TABLE ods.news_articles
  ADD CONSTRAINT news_articles_pkey PRIMARY KEY (id);

ALTER TABLE ods.news_articles
  ADD CONSTRAINT news_articles_url_key UNIQUE (url);

CREATE INDEX idx_news_articles_related_stocks ON ods.news_articles USING gin (related_stocks);